// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4FCEkf3SVM6F6mMy6KgRZSVIOAgziRMU',
    appId: '1:713345790986:web:13abddcb407670e96f9bf3',
    messagingSenderId: '713345790986',
    projectId: 'flutter-app-login-b932e',
    authDomain: 'flutter-app-login-b932e.firebaseapp.com',
    storageBucket: 'flutter-app-login-b932e.firebasestorage.app',
    measurementId: 'G-GCV8LL9HFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3n5faSf86atpBg1cMY6WtBstBYiJUOFs',
    appId: '1:713345790986:android:60da06d02b7dc96b6f9bf3',
    messagingSenderId: '713345790986',
    projectId: 'flutter-app-login-b932e',
    storageBucket: 'flutter-app-login-b932e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYBoIG-vM1V-YktQBEoYFwnsqv5ZdFdCU',
    appId: '1:713345790986:ios:6d91975087b76aa56f9bf3',
    messagingSenderId: '713345790986',
    projectId: 'flutter-app-login-b932e',
    storageBucket: 'flutter-app-login-b932e.firebasestorage.app',
    androidClientId: '713345790986-6dje2juap96tk3ug439tnq37lvdaot22.apps.googleusercontent.com',
    iosClientId: '713345790986-jocc18mhdm325g0sru92p1c8cpfrqvri.apps.googleusercontent.com',
    iosBundleId: 'com.example.medichealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYBoIG-vM1V-YktQBEoYFwnsqv5ZdFdCU',
    appId: '1:713345790986:ios:6d91975087b76aa56f9bf3',
    messagingSenderId: '713345790986',
    projectId: 'flutter-app-login-b932e',
    storageBucket: 'flutter-app-login-b932e.firebasestorage.app',
    androidClientId: '713345790986-6dje2juap96tk3ug439tnq37lvdaot22.apps.googleusercontent.com',
    iosClientId: '713345790986-jocc18mhdm325g0sru92p1c8cpfrqvri.apps.googleusercontent.com',
    iosBundleId: 'com.example.medichealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4FCEkf3SVM6F6mMy6KgRZSVIOAgziRMU',
    appId: '1:713345790986:web:99374ae87ddd3a196f9bf3',
    messagingSenderId: '713345790986',
    projectId: 'flutter-app-login-b932e',
    authDomain: 'flutter-app-login-b932e.firebaseapp.com',
    storageBucket: 'flutter-app-login-b932e.firebasestorage.app',
    measurementId: 'G-9L6F5D19F4',
  );
}
